export interface Vehicle {
  vehicle_id?: number;
  vehicle_make_id: number;
  vehicle_model_id: number;
  vehicle_variant_id: number;
  manufacturing_year?: string | null;
  vehicle_type_id?: number | null;
  fuel_type_id?: number | null;
  transmission_type_id?: number | null;
  vehicle_ownership_type_id?: number | null;
  vehicle_category_id?: number | null;
  vehicle_subcategory_id?: number | null;
  seller_id: number;
  regs_no?: string | null;
  vehicle_location?: string | null;
  vehicle_manager_id?: number | null;
  base_price?: number | null;
  max_price?: number | null;
  bid_finalised?: number | null;
  auction_end_dttm?: string | null;
  additional_remarks?: string | null;
  notes?: string | null;
  top_bidder_id?: number | null;
  bidders_count?: number | null;
  added_by_id?: number | null;
  updated_by_id?: number | null;
  added_on?: string | null;
  updated_on?: string | null;
  address?: string | null;
  auction_start_dttm?: string | null;
  auction_type?: number | null;
  challan_amt?: number | null;
  chasis_no?: string | null;
  color?: string | null;
  engine_no?: string | null;
  fitness_validity?: string | null;
  loan_disbursment_dt?: string | null;
  odometer_reading?: number | null;
  ownership_serial?: string | null;
  parking_charges?: number | null;
  pending_challans?: number | null;
  permit_type?: number | null;
  permit_validity?: string | null;
  rc_availability?: number | null;
  registeration_type_id?: number | null;
  registration_year?: string | null;
  repo_date?: string | null;
  reserve_price?: number | null;
  road_tax_validity?: string | null;
  rto_dtls?: string | null;
  running_status?: number | null;
  seller_manager?: string | null;
  seller_reference?: string | null;
  vehicle_address_zip?: string | null;
  vehicle_city_id?: number | null;
  vehicle_state_id?: number | null;
  auction_status_id?: number | null;
  vehicle_image_id?: number | null;
  expected_price?: number | null;
  business_vertical: string;
}


