services:
  redis-local:
    image: redis:7-alpine
    container_name: kmsg-redis-local
    restart: unless-stopped
    ports:
      - "6380:6379"  # host 6380, container 6379
    networks:
      - kmsg_buyer_net

networks:
  kmsg_buyer_net:
    external: true
