version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kmsgdb
      MYSQL_USER: kmsguser
      MYSQL_PASSWORD: kmsgpass
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
